version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: perfume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - test-network

  rest-ecommerce:
    image: dsoft-ecommerce-spring
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-ecommerce
    ports:
      - "8080:8080"
    networks:
      - test-network
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/perfume
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

networks:
  test-network:
    driver: bridge