name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          config: |
            [[rules]]
              description = "Generic API Key"
              regex = '''(?i)(key|api|token|secret)[. \-_]*([a-z0-9]{32,128})'''  
          redact: true                 
          exit-code: 0   
